import type {
  TeachingPackage,
  Remix,
  DiscussionPost,
  Contributor,
  ArtifactFile,
  PackageSummary,
  WsaSchool,
} from './types';

// Mock data for 1.1-III teaching package
// Source: community_cce_tw/mockups/detail_page.html
// Will be replaced by GitHub API + Firestore in Phase 0 Week 1-2 sprint.

export const teachingPackage: TeachingPackage = {
  keyId: '1.1-III',
  level: 'III',
  topic: '天氣、氣候與氣候變遷',
  topicEn: 'Weather, climate and climate change',
  ageBand: '9–12 歲',
  themeNumber: 1,
  themeName: '氣候科學',
  stars: 24,
  forks: 12,
  publishedAt: '2026-04-16',
  keyIdea: '全球平均氣溫正在上升，極端天氣事件愈來愈頻繁。',
  learningOutcomes: {
    cognitive: [
      'C1 氣溫長期變化與工業革命',
      'C2 臺灣氣溫範圍調查',
      'C3 解釋「全球暖化」意義',
      'C4 季節變異 vs 整體上升趨勢',
      'C5 全球與在地暖化影響',
    ],
    social: [
      'S1 表達對行動的感受（希望、被賦能）',
      'S2 連結正向情緒與氣候行動',
    ],
    behavioural: [
      'B1 與家人/社群合作，預防、減緩、調適在地氣候風險',
    ],
  },
};

export const remixes: Remix[] = [
  {
    authorName: '陳雅婷',
    authorSchool: '台北 OO 國小',
    publishedAt: '2026-05-12',
    summary: '加入北市溫度資料 · 適用都市場景',
    stars: 8,
    forks: 12,
    applicableCity: '台北市',
  },
  {
    authorName: '林志明',
    authorSchool: '高雄 XX 國小',
    publishedAt: '2026-06-03',
    summary: '改為高雄氣候、加入在地案例（高雄港海平面、左營熱島）',
    stars: 5,
    forks: 3,
    applicableCity: '高雄市',
  },
  {
    authorName: '王美玲',
    authorSchool: '彰化 ZZ 國小',
    publishedAt: '2026-07-18',
    summary: '加入英語雙語版本 · 適用雙語實驗班',
    stars: 3,
    forks: 1,
    applicableCity: '彰化縣',
  },
];

export const contributors: Contributor[] = [
  { initial: '計', name: '計畫團隊', school: '官方原作', gradientFrom: '#E8884F', gradientTo: '#C96E34' },
  { initial: '陳', name: '陳雅婷', school: '台北 OO 國小', gradientFrom: '#3C6E47', gradientTo: '#2A5A38' },
  { initial: '林', name: '林志明', school: '高雄 XX 國小', gradientFrom: '#8B5A3C', gradientTo: '#5E3B24' },
  { initial: '王', name: '王美玲', school: '彰化 ZZ 國小', gradientFrom: '#C96E34', gradientTo: '#8B5A3C' },
];

export const discussionPosts: DiscussionPost[] = [
  {
    authorName: '張老師',
    authorSchool: '台中 OO 國小',
    postedAgo: '3 天前',
    tag: { label: '💡 建議', type: 'suggestion' },
    content: '可以加入颱風實例嗎？我們班在海線，學生對颱風很有感，想連結到氣候變遷造成的強度增加。',
    replies: 5,
    likes: 12,
  },
  {
    authorName: '李老師',
    authorSchool: '花蓮 XX 國小',
    postedAgo: '1 週前',
    tag: { label: '👍 試教回饋', type: 'feedback' },
    content: '試教反應很好，學生都很投入！第 3 節的情緒盤點特別有感，有學生哭了但也有學生說「我想從現在開始做點什麼」。',
    replies: 2,
    likes: 18,
  },
  {
    authorName: '黃老師',
    authorSchool: '新北 △△ 國小',
    postedAgo: '2 週前',
    tag: { label: '❓ 問題', type: 'question' },
    content: '第 2 節的 TCCIP 資料連結有時候會掛掉，有沒有備援的資料來源可以用？',
    replies: 3,
    likes: 5,
  },
  {
    authorName: '蔡老師',
    authorSchool: '宜蘭 ◇◇ 國小',
    postedAgo: '3 週前',
    content: '建議可以搭配校外教學到在地氣象站，學生對真實儀器的反應比圖表強很多。',
    replies: 1,
    likes: 7,
  },
];

// All packages shown on the home/search page.
// Only '1.1-III' has a full detail page wired up in this POC — others render a placeholder.
export const allPackages: PackageSummary[] = [
  {
    keyId: '1.1-II',
    level: 'II',
    levelLabel: '幼兒園低年級',
    topic: '小熊波波的天氣日記',
    themeNumber: 1,
    themeName: '氣候科學',
    summary: '用繪本故事帶幼兒認識四季與天氣變化，適合引導式情境教學。',
    stars: 6,
    forks: 2,
    contributors: 1,
    emojis: '🐻☁️',
  },
  {
    keyId: '1.1-III',
    level: 'III',
    levelLabel: '國小中高',
    topic: '天氣、氣候與氣候變遷',
    themeNumber: 1,
    themeName: '氣候科學',
    summary: '以臺灣氣溫資料切入，4 節 × 40 分鐘，涵蓋認知、情緒與行動。',
    stars: 24,
    forks: 12,
    contributors: 4,
    emojis: '🌡️📈',
    isOfficial: true,
    hasDetail: true,
  },
  {
    keyId: '1.2-IV',
    level: 'IV',
    levelLabel: '國中',
    topic: '溫室氣體與全球碳循環',
    themeNumber: 1,
    themeName: '氣候科學',
    summary: '理解 CO₂、CH₄、N₂O 的來源與影響，操作 IPCC 簡化模擬器。',
    stars: 18,
    forks: 4,
    contributors: 2,
    emojis: '💨🌫️',
  },
  {
    keyId: '2.1-III',
    level: 'III',
    levelLabel: '國小中高',
    topic: '小海龜的旅程：海洋生態系',
    themeNumber: 2,
    themeName: '生態系與生物多樣性',
    summary: '透過綠蠵龜遷徙故事，認識珊瑚礁、洋流與塑膠污染之間的連動。',
    stars: 31,
    forks: 9,
    contributors: 3,
    emojis: '🐢🌊',
  },
  {
    keyId: '2.4-V',
    level: 'V',
    levelLabel: '高中',
    topic: '永續飲食與糧食系統',
    themeNumber: 2,
    themeName: '生態系與生物多樣性',
    summary: '分析食物里程、土地使用與蛋白質選擇，設計低碳校園菜單。',
    stars: 22,
    forks: 6,
    contributors: 2,
    emojis: '🥗🌾',
  },
  {
    keyId: '3.1-III',
    level: 'III',
    levelLabel: '國小中高',
    topic: '誰先受到氣候衝擊？',
    themeNumber: 3,
    themeName: '氣候正義',
    summary: '從太平洋島國、原住民社群出發，認識氣候脆弱度的不平等。',
    stars: 15,
    forks: 3,
    contributors: 2,
    emojis: '⚖️🌍',
  },
  {
    keyId: '4.3-IV',
    level: 'IV',
    levelLabel: '國中',
    topic: '面對氣候焦慮：情緒盤點',
    themeNumber: 4,
    themeName: '韌性建構',
    summary: '帶學生辨識氣候焦慮、悲傷與無力感，學習轉化為行動動能。',
    stars: 27,
    forks: 5,
    contributors: 3,
    emojis: '🧠💧',
  },
  {
    keyId: '5.2-II',
    level: 'II',
    levelLabel: '幼兒園低年級',
    topic: '玩具的第二個生命',
    themeNumber: 5,
    themeName: '後碳經濟',
    summary: '透過玩具交換會與修理工作坊，讓幼兒理解重複使用的意義。',
    stars: 9,
    forks: 1,
    contributors: 1,
    emojis: '♻️🧸',
  },
  {
    keyId: '6.6-V',
    level: 'V',
    levelLabel: '高中',
    topic: '設計屬於你的永續飲食提案',
    themeNumber: 6,
    themeName: '永續生活形態',
    summary: '高中專題課程，整合 SDG2、SDG12、SDG13，產出一份可落地的社區提案。',
    stars: 20,
    forks: 4,
    contributors: 2,
    emojis: '🍱🌱',
  },
];

export const wsaSchools: WsaSchool[] = [
  { name: '台北 OO 國小', icon: '🏯', focus: '推動主題：都市熱島與綠屋頂', teachers: 6, remixes: 15 },
  { name: '高雄 XX 國小', icon: '⚓', focus: '推動主題：海洋生態與塑膠循環', teachers: 8, remixes: 12 },
  { name: '新竹 YY 國小', icon: '🔬', focus: '推動主題：科技園區與能源', teachers: 5, remixes: 9 },
  { name: '彰化 ZZ 國小', icon: '🌾', focus: '推動主題：農業與在地糧食', teachers: 9, remixes: 6 },
];

export const artifactFiles: ArtifactFile[] = [
  {
    name: '數據資料卡',
    filename: 'data_card.json',
    description: '5 個可靠來源的數據點（NASA、TCCIP、IPCC）',
    icon: '📊',
    bgClass: 'bg-forest/10',
  },
  {
    name: '教案',
    filename: 'lesson_plan.md',
    description: '4 節 × 40 分鐘完整教案、流程表、形成性評量',
    icon: '📝',
    bgClass: 'bg-sun/15',
  },
  {
    name: '簡報腳本',
    filename: 'ppt_script.md',
    description: '22 張投影片講者稿，含提問與轉場',
    icon: '🎯',
    bgClass: 'bg-earth/15',
  },
  {
    name: '互動學習單',
    filename: 'worksheet.html',
    description: '學生用 HTML 互動頁，可在平板/桌機直接填寫',
    icon: '🎮',
    bgClass: 'bg-sun/20',
    highlight: true,
    previewUrl: 'https://yujchang2017.github.io/cce-teaching-packages/packages/level-iii/1.1-III/worksheet.html',
  },
];
